# Application
spring.application.name=Security

# Server port  
server.port=${PORT:8080}

# Data source: H2 for local dev (default). Use profile 'railway' for PostgreSQL on Railway.
#spring.datasource.url=jdbc:h2:mem:authdb
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Support HTTP methods PUT, PATCH, DELETE
spring.mvc.hiddenmethod.filter.enabled=true

##################
# Используем переменную среды DATABASE_URL от Render
#spring.datasource.url=${jdbc:postgresql://users_p556_user:rVUWaX5uBs0UUQ0ezST0B6tcP2Aol484@dpg-d6op1nhaae7s73a91rrg-a/users_p556}
spring.datasource.url=jdbc:postgresql://dpg-d6op1nhaae7s73a91rrg-a/users_p556
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${users_p556}       # Render может предоставить эти переменные
spring.datasource.password=${rVUWaX5uBs0UUQ0ezST0B6tcP2Aol484}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Render назначает порт через переменную PORT
#server.port=${PORT:8080}

